### ISSUE TITLE
plugin fails due to content-length randmonly

### ISSUE THREAD

**Issue by lukeaduncan** [cqframework/vscode-cql#37]
Using the preview release (0.7.0) I sometimes get this error in the extensions log:

```
2024-03-06 09:32:50.369 [error] Error: Header must provide a Content-Length property.
	at StreamMessageReader.onData (/home/lduncan/.vscode/extensions/cqframework.cql-0.7.0/node_modules/vscode-jsonrpc/lib/common/messageReader.js:138:27)
	at Socket.<anonymous> (/home/lduncan/.vscode/extensions/cqframework.cql-0.7.0/node_modules/vscode-jsonrpc/lib/common/messageReader.js:122:18)
	at Socket.emit (node:events:514:28)
	at addChunk (node:internal/streams/readable:324:12)
	at readableAddChunk (node:internal/streams/readable:297:9)
	at Socket.push (node:internal/streams/readable:234:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

The results output just stops with no additional message:

```
Executing CQL...
CQL path: /home/lduncan/Documents/github/PATH/smart-immunizations/smart-immunizations/input/cql
Data path: /home/lduncan/Documents/github/PATH/smart-immunizations/smart-immunizations/input/tests/plandefinition/IMMZD2DTHepatitisB3OnTime
Terminology path: /home/lduncan/Documents/github/PATH/smart-immunizations/smart-immunizations/input/vocabulary/valueset
```

I have to manually kill the java process and restart vscode to get it working again.

**Comment by brynrhodes** [comment]
@lukeaduncan can you confirm if this issue is still occurring?
